### ISSUE TITLE
can't load profiles with latest vernier?

### ISSUE THREAD

**Issue by zenspider** [jhawthorn/vernier#118]
I'm not sure if this is a problem with vernier or if profile-viewer needs to be updated... but I just did a gem bump of vernier to 1.5.0 and profile-viewer is up to date and now I'm getting this when I try to load a profile:

<img width="607" alt="image" src="https://github.com/user-attachments/assets/e2a0b3f1-d7c8-4f6f-ab89-1d590b87aa52" />

`jq .` has no problem with the file at all so I'm not sure what's up.

I can provide a profile if that'll help, but I'm guessing this problem is generic enough? I'm not doing anything special.

**Comment by zenspider** [comment]
OK. Guessing this is a problem with profile-viewer because vernier.prof loads the files fine. Feel free to transfer this issue over or I can repost there.

**Comment by jedschneider** [comment]
It doesn't look like `profile-viewer` is setup with issues to report there, but i agree with your assessment, vernier is publishing a metadata and json payload that is a version ahead of what profile-viewer can accept at the moment. You can upload a profile directly to the profiler.firefox.com website that is produced by vernier 1.5.

**Comment by joshuay03** [comment]
Looks like a [new version](https://github.com/tenderlove/profiler/releases/tag/v0.0.3) of `profile-viewer` was released a few days ago with support for the current vernier profiler version, can you try that?

**Comment by joshuay03** [comment]
Hmm the latest `profile-viewer` works fine locally but the bundle in the actual release seems to be invalid. The public paths in `dist/` are being prefixed with `/sidekiq` cc/ @tenderlove

**Comment by tenderlove** [comment]
Oh gosh, I probably broke it

**Comment by tenderlove** [comment]
Looks like the yarn recompilation didn't do what I expected it to do. I've shipped a new version that should work correctly.

**Comment by joshuay03** [comment]
Seems to be working now 👍🏽

**Comment by zenspider** [comment]
confirmed. thanks y'all!
