### ISSUE TITLE
We should gzip by default

### ISSUE THREAD

**Issue by jhawthorn** [jhawthorn/vernier#47]
The viewer supports it, so let's do it always

**Comment by dalehamel** [comment]
I have seen some vernier profiles that are 100MB+ (lots of threads I guess?), gzipped they are about 15Mb, so there is definitely a case for this.

**Comment by mikebaldry** [comment]
How do you want to handle this? I've implemented it in a simple way (`compress` is an option and it defaults to `true`) but not sure that is ideal. You'll end up with `.json` files that are actually `.json.gz` contents.. I was thinking maybe do it automatically, only if you specify `.gz` as the filename, or you explicitly pass `compress: true`

**Comment by jhawthorn** [comment]
@mikebaldry Sorry! I missed your comment. I implemented this in https://github.com/jhawthorn/vernier/commit/1cee8309eb1f9130a4d0942363b3f770d4232350
