### ISSUE TITLE
Explicit selection of threads in firefox output

### ISSUE THREAD

**Issue by jhawthorn** [jhawthorn/vernier#56]
The firefox profiler makes a guess at which threads to hide and which to have selected by default. Currently we let it do this.

When profiling is started from a non-main thread it's probably best to pre-select that thread, assuming that the user wanted to profile something in that thread (though there are certainly cases that doesn't make sense, so we may want to adjust that heuristic).

**Comment by joshuay03** [comment]
> (though there are certainly cases that doesn't make sense, so we may want to adjust that heuristic).

Did you have an example case in mind?

I got #75 up which ensures the thread which starts the collector is set as the main thread.
