### ISSUE TITLE
self-hosted vernier.prof?

### ISSUE THREAD

**Issue by technicalpickles** [jhawthorn/vernier#74]
What powers https://vernier.prof ? I'm wondering if it would be possible to have something self-hosted for an organization, such that you capture and then upload the profile to something that can be shared.

Is it just running https://github.com/tenderlove/profiler ?

**Comment by jhawthorn** [comment]
Yes! It's just https://github.com/tenderlove/profiler, plus a server running on `gems.vernier.prof` which I'll try to publish shortly. You can also run on localhost using `profile-viewer`
