### ISSUE TITLE
[bug] Possible for frame entry in stack table to be null

### ISSUE THREAD

**Issue by dalehamel** [jhawthorn/vernier#85]
A production app generated profiles which failed to load in any version of firefox-profiler we tried. One of our devs filed this issue upstream https://github.com/firefox-devtools/profiler/issues/5074, but I believe the true issue is that the output from vernier is not a valid gecko profile.

The profile does not load in https://vernier.prof either. Here is [the profile](https://github.com/user-attachments/files/16616929/20240814-132029-wall-2495f481-c7b4-48c1-bb05-6125da93e2ae-1723641627-web-67f44cb4b4-8wbz4.gecko.json).

Looking closely at the error, I was able to determine that a thread has an invalid stack table:

```
    {
      "name": "(2051520)",
      "isMainThread": false,
      "processStartupTime": 995739.389136,
      "registerTime": 995739.389136,
      "pausedRanges": [],
      "pid": 123,
      "tid": 0,
      "frameTable": {
        "address": [],
        "inlineDepth": [],
        "category": [],
        "subcategory": null,
        "func": [],
        "nativeSymbol": [],
        "innerWindowID": [],
        "implementation": [],
        "line": [],
        "column": [],
        "length": 0
      },
      "funcTable": {
        "name": [],
        "isJS": [],
        "relevantForJS": [],
        "resource": [],
        "fileName": [],
        "lineNumber": [],
        "columnNumber": [],
        "length": 0
      },
      "nativeSymbols": {},
      "samples": {
        "stack": [
          0,
          1
        ],
        "weight": [
          1,
          1032
        ],
        "weightType": "samples",
        "length": 2
      },
      "stackTable": {
        "frame": [
          null,
          null
        ],
        "category": [
          2,
          1
        ],
        "subcategory": [
          0,
          0
        ],
        "prefix": [
          null,
          null
        ],
        "length": 2
      },

```

The root cause seems to be that the "frame" entry itself is somehow "null". This gets input as a numeric index, and ends up exploding in the UI.

If I delete the invalid thread, the [profile](https://github.com/user-attachments/files/16616989/fixed.gecko.json) can now be displayed.

This seems like a legitimate bug in vernier, as we're somehow getting invalid output where the top stack frame references a null value, which is an invalid index into the frame table. The frametable is also empty, as the example shows.

**Comment by dalehamel** [comment]
Note that the profile was generated from the latest released version of vernier, 1.1.1

**Comment by Earlopain** [comment]
I'm encountering the same thing. I'm profiling something with `bundler/inline` and I believe the issue has something to do with me specifying git dependencies:

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
end
```

This consistently produces a profile I'm unable to load for what I assume are the same reasons as OP. [trace.json](https://github.com/user-attachments/files/16637060/trace.json)

I run vernier like so: `vernier run --output trace.json -- ruby test.rb`

**Comment by Earlopain** [comment]
Reduced it a bit further and it seems to boil down to this:

```rb
# frozen_string_literal: true

require "open3"
Open3.capture3("sleep", "1")
```

[trace.json](https://github.com/user-attachments/files/16644740/trace.json)

I've tried it with plain `sleep 1` in backticks but that works fine so it seems specific to something the `open3` gem does.

**Comment by jhawthorn** [comment]
Thank you both! I just merged https://github.com/jhawthorn/vernier/pull/89 which should fix this and released that as 1.1.2

**Comment by Earlopain** [comment]
This works nicely, thanks!

**Comment by dalehamel** [comment]
@jhawthorn thank you! We'll try it out and report back if it is not resolved.
